Improved handling of failed tests

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -45,10 +45,19 @@ jobs:
       - name: Run Robot tests
         run: |
           bash scripts/tests.sh
+          continue-on-error: true
 
       # Upload test results to workflow artifacts
       - name: Upload Robot logs
+        if: always()
         uses: actions/upload-artifact@v4
         with:
           name: robot-results
           path: results/
+
+      # Fail workflow if any tests failed
+      - name: Fail workflow if robot tests failed
+        if: steps.robot.outcome == 'failure'
+        run: |
+          echo "Robot tests failed."
+          exit 1
